---

- hosts: decapod-mirrors
  tasks:
    - include: ./tasks/subrepo.yml
      with_dict: "{{ supported_releases }}"
    - include: ./tasks/rsync.yml
      with_dict: "{{ supported_releases }}"
  vars:
    repo_root: "{{ subrepos_root }}"

- hosts: decapod-mirros-dbg
  tasks:
    - include: ./tasks/subrepo.yml
      with_dict: "{{ supported_releases }}"
  vars:
    repo_root: "{{ subrepos_root }}-dbg"
    debug_symbols_only: true
